[phases.setup]
commands = [
    "pip install --upgrade pip"
]

[phases.install]
commands = [
    "pip install -r requirements.txt"
]

[phases.migrate]
commands = [
    "python manage.py migrate --noinput"
]

[phases.build]
commands = [
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn earning_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile -"
